server:
  port: 9001

spring:
  application:
    name: BOOK-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey